### ISSUE TITLE
Неверный индекс у div'а с 

### ISSUE THREAD

**Issue by Kotaviy** [Kotaviy/PageObject#1]
# Шаги воспроизведения
1. Открыть [проект](https://github.com/Kotaviy/PageObject) в IDEA
2. Запустить [локальный сервер](https://github.com/Kotaviy/PageObject/blob/main/artifacts/app-ibank-build-for-testers.jar) в терминале.
3. Запустить TransferTest IDEA.
4. Дождаться результат в терминале.
## Ожидаемый результат
Тесты проходят, показывается текущий баланс карт.
## Фактический результат
Тесты не проходят (неверный индекс у элемента div), показывается текущий баланс карт.
# Скриншот
![Ошибка в тесте](https://github.com/Kotaviy/PageObject/assets/86298028/55c04c4c-2b84-4961-8365-1eada7361032)
# Окружение
* Операционная система: Windows 10
* IDE: IntelliJ IDEA Community Edition 2023.1.1
* Java: OpenJDK 11

**Comment by andrew-pahomov** [comment]
Тут https://github.com/Kotaviy/PageObject/blob/6561c1c4ae6b0d46c1ac165eec7ecc6f8d70a6da/src/test/java/page/DashboardPage.java#L17C50-L17C66 некорректный селектор, посморите инструкцию https://github.com/netology-code/aqa-homeworks/blob/master/bdd/balance.md

**Comment by Kotaviy** [comment]
Проблема решена
